target-dir: "/path/to/build"
clean: true                     #Removes current content from the target directory
clean-exceptions:               #Files or directories that should be kept during cleaning (local to target-dir)
  - "path/to/file"
  - "path/to/directory/"

link-dir-paths:                 #List of directories to hard link into target directory
  - "/path/to/dir1"
  - "/path/to/dir2"

copy-dir-paths:                 #List of directories to copy into target directory
  - "path/to/dir3"
  - "path/to/dir4"

composer: true                  #Should composer be run
update: false                   #If true, composer update will be run. If false, composer install will be run.
no-dev: false                   #Should composer be run with --no-dev
post-composer-dir-paths:        #List of directories to symlink into target directory after running composer
  - "/post/composer/path1"
  - "/post/composer/path2"

grunt: true                     #Should grunt be run
grunt-tasks:
  - "task1"
  - "task2"
  - "task3"
